### ISSUE TITLE
regarding LICENSE

### ISSUE THREAD

**Issue by hakanrw** [oyama/pico-usb-flash-drive#1]
Dear Oyama,

I would like to integrate your FAT12 filesystem library into my project. However, the lack of a license makes it difficult for me to use it. Could you please clarify the licensing terms for your library? Having a clear license would help ensure that I can use, modify, and distribute the library in compliance with your terms.

Thank you for your understanding and hard work.

Best regards,
Hakan

**Comment by oyama** [comment]
Thanks for your comment.

[LICENSE.md](https://github.com/oyama/pico-usb-flash-drive/blob/main/LICENSE.md) file added. All code in this project is under the BSD-3-Clause licence.
